export const UserTypes = {
    SET_USER: 'user/SET_USER',
    SET_LOADING_STATE: 'user/SET_LOADING_STATE',
    FETCH_SIGN_IN_USER: 'user/FETCH_SIGN_IN_USER',
    FETCH_SIGN_UP_USER: 'user/FETCH_SIGN_UP_USER',
    FETCH_USER_DATA: 'user/FETCH_USER_DATA',

}